name: rpm
author: vu-ase
source: github.com/VU-ASE/rpm
version: 1.0.0
description: Service to read RPM and speed values for both rear wheels

commands:
  build: make build
  run: ./bin/rpm

inputs: []
outputs:
  - rpm

configuration: []
